// utils/skillsImage.ts
const map: Record<string, string> = {
  "gcp": "/svg/skills/gcp.svg",
  "html": "/svg/skills/html.svg",
  "photoshop": "/svg/skills/photoshop.svg",
  "illustrator": "/svg/skills/illustrator.svg",
  "docker": "/svg/skills/docker.svg",
  "adobe xd": "/svg/skills/adobe-xd.svg",
  "after effects": "/svg/skills/after-effects.svg",
  "css": "/svg/skills/css.svg",
  "angular": "/svg/skills/angular.svg",
  "javascript": "/svg/skills/javascript.svg",
  "next js": "/svg/skills/nextJS.svg",
  "nuxt js": "/svg/skills/nuxtJS.svg",
  "react": "/svg/skills/react.svg",
  "svelte": "/svg/skills/svelte.svg",
  "typescript": "/svg/skills/typescript.svg",
  "vue": "/svg/skills/vue.svg",
  "bootstrap": "/svg/skills/bootstrap.svg",
  "bulma": "/svg/skills/bulma.svg",
  "capacitorjs": "/svg/skills/capacitorjs.svg",
  "coffeescript": "/svg/skills/coffeescript.svg",
  "memsql": "/svg/skills/memsql.svg",
  "mongodb": "/svg/skills/mongoDB.svg",
  "mysql": "/svg/skills/mysql.svg",
  "postgresql": "/svg/skills/postgresql.svg",
  "tailwind": "/svg/skills/tailwind.svg",
  "vitejs": "/svg/skills/vitejs.svg",
  "vuetifyjs": "/svg/skills/vuetifyjs.svg",
  "c": "/svg/skills/c.svg",
  "c++": "/svg/skills/cplusplus.svg",
  "c#": "/svg/skills/csharp.svg",
  "dart": "/svg/skills/dart.svg",
  "go": "/svg/skills/go.svg",
  "java": "/svg/skills/java.svg",
  "julia": "/svg/skills/julia.svg",
  "kotlin": "/svg/skills/kotlin.svg",
  "matlab": "/svg/skills/matlab.svg",
  "php": "/svg/skills/php.svg",
  "python": "/svg/skills/python.svg",
  "ruby": "/svg/skills/ruby.svg",
  "swift": "/svg/skills/swift.svg",
  "adobe audition": "/svg/skills/adobeaudition.svg",
  "aws": "/svg/skills/aws.svg",
  "deno": "/svg/skills/deno.svg",
  "django": "/svg/skills/django.svg",
  "firebase": "/svg/skills/firebase.svg",
  "gimp": "/svg/skills/gimp.svg",
  "git": "/svg/skills/git.svg",
  "graphql": "/svg/skills/graphql.svg",
  "lightroom": "/svg/skills/lightroom.svg",
  "materialui": "/svg/skills/materialui.svg",
  "nginx": "/svg/skills/nginx.svg",
  "numpy": "/svg/skills/numpy.svg",
  "opencv": "/svg/skills/opencv.svg",
  "premiere pro": "/svg/skills/premierepro.svg",
  "pytorch": "/svg/skills/pytorch.svg",
  "selenium": "/svg/skills/selenium.svg",
  "strapi": "/svg/skills/strapi.svg",
  "tensorflow": "/svg/skills/tensorflow.svg",
  "webix": "/svg/skills/webix.svg",
  "wordpress": "/svg/skills/wordpress.svg",
  "azure": "/svg/skills/azure.svg",
  "blender": "/svg/skills/blender.svg",
  "fastify": "/svg/skills/fastify.svg",
  "figma": "/svg/skills/figma.svg",
  "flutter": "/svg/skills/flutter.svg",
  "haxe": "/svg/skills/haxe.svg",
  "ionic": "/svg/skills/ionic.svg",
  "markdown": "/svg/skills/markdown.svg",
  "microsoft office": "/svg/skills/microsoftoffice.svg",
  "picsart": "/svg/skills/picsart.svg",
  "sketch": "/svg/skills/sketch.svg",
  "unity": "/svg/skills/unity.svg",
  "wolframalpha": "/svg/skills/wolframalpha.svg",
  "canva": "/svg/skills/canva.svg"
};

export const skillsImage = (skill: string): string | undefined => {
  const key = skill.trim().toLowerCase();
  return map[key];
};